---
# tasks file for docker
- name: 1 - Ping-able?
  ping:

- name: 2 - Install Docker
  apt:
    name: docker.io
    state: present

- name: 3 - Update cgroupdriver to systemd
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: 4 - Update sandbox image of containerd
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: 5 - Reload Docker
  service:
    name: docker
    state: reloaded

- name: 6 - Restart Docker
  service:
    name: docker
    state: restarted

- name: 7 - Restart Containerd
  service:
    name: containerd
    state: restarted
