---
# tasks file for os_kernel

- name: 1 - Ping-able?
  ping:

- name: 2 - Add br_netfilter to module load
  copy:
    dest: /etc/modules-load.d/br_netfilter.conf
    content: |
      br_netfilter

- name: 3 - Enable br_netfilter
  modprobe: 
    name: br_netfilter
    state: present

- name: 4 - IPv4 & IPv6 net forwarding conf
  copy:
    dest: /etc/sysctl.d/forwarding.conf
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      vm.swappiness = 0

- name: 5 - Apply conf
  command: sysctl --system
